#ifndef inclguard_configuration_h
#define inclguard_configuration_h

/* WARNING:
 * do NOT edit this file if you don't exactly know what you're doing.
 * Some of these settings require to be configured in pair with RX settings.
 * Read nrf24l01+ datasheet before editing these settings. I told you.
 */

/* nrf24l01+ configuration */

// Payload size, defined from application
#define CFG_PAYLOAD_SIZE         21

/* Transmission power. Possible values are
 *
 *         NRFCFG_POWER_0dbm    :   0 dBm
 *         NRFCFG_POWER_m6dbm   :  -6 dBm
 *         NRFCFG_POWER_m12dbm  : -12 dBm
 *         NRFCFG_POWER_m18dbm  : -18 dBm
 */
#define CFG_TX_POWER             NRFCFG_POWER_0dbm

/* Delay in 250us steps to wait before retransmitting, if AUTOACK is required
 * but is not received. From 1 to 16
 * Should NEVER be less than 6
 */
#define CFG_RETRANSMIT_DELAY     10

/* Maximum times to attempt retransmission if AUTOACK is required
 * but is not received.
 * From 0 (do not retransmit) to 15
 */
#define CFG_MAX_RETRANSMIT       15

/* Radio channel to use (from 0 to 127)
 * Must be the same programmed on the RX
 */
#define CFG_RADIO_CHANNEL        121

/* 1 to require acknowledge from receiver, 0 otherwise
 * Must be the same programmed on the RX
 */
#define CFG_USE_AUTOACK          1

/* Use CRC to validate packet transmission. Possible values are
 *
 *         NRFCFG_NO_CRC : do not use CRC
 *         NRFCFG_CRC_1B : use 1-byte CRC (simple)
 *         NRFCFG_CRC_2B : use complex 2-byte CRC
 *
 * Must be the same programmed on the RX
 */
#define CFG_USE_CRC              NRFCFG_CRC_2B

/* Transmission data rate. Possible values are
 *
 *         NRFCFG_DATARATE_250k : 250 kbps
 *         NRFCFG_DATARATE_1M   : 1 Mbps
 *         NRFCFG_DATARATE_2M   : 2 Mbps
 *
 * Must be the same programmed on the RX
 */
#define CFG_DATARATE             NRFCFG_DATARATE_250k

/* Number of bytes forming address. from 3 to 5
 * Must be the same programmed on the RX
 */
#define CFG_NUM_ADDRESS_BYTES    5

/* Bytes forming address.
 * from 3 to 5 comma separated bytes (according to CFG_NUM_ADDRESS_BYTES)
 *
 * Must be the same programmed on an active pipe in the RX
 */
#define CFG_ADDRESS              71, 55, 93, 7, 43

/* Validation section. do not edit this. **************************************/
 
#if (CFG_TX_POWER != NRFCFG_POWER_0dbm && CFG_TX_POWER != NRFCFG_POWER_m6dbm && \
    CFG_TX_POWER != NRFCFG_POWER_m12dbm && CFG_TX_POWER != NRFCFG_POWER_m18dbm)
     #error Invalid NRFCFG_POWER setting
#endif
#if (CFG_RETRANSMIT_DELAY < 6 || CFG_RETRANSMIT_DELAY > 16)
     #error Invalid CFG_RETRANSMIT_DELAY setting
#endif
#if (CFG_MAX_RETRANSMIT < 0 || CFG_MAX_RETRANSMIT > 15)
     #error Invalid CFG_MAX_RETRANSMIT setting
#endif
#if (CFG_RADIO_CHANNEL < 0 || CFG_RADIO_CHANNEL > 127)
     #error Invalid CFG_RADIO_CHANNEL setting
#endif
#if (CFG_USE_AUTOACK != 1 && CFG_USE_AUTOACK != 0)
     #error Invalid CFG_USE_AUTOACK setting
#endif
#if (CFG_USE_CRC != NRFCFG_NO_CRC && CFG_USE_CRC != NRFCFG_CRC_1B && \
    CFG_USE_CRC != NRFCFG_CRC_2B)
     #error Invalid CFG_USE_CRC setting
#endif
#if (CFG_DATARATE != NRFCFG_DATARATE_250k && CFG_DATARATE != NRFCFG_DATARATE_1M && \
    CFG_DATARATE != NRFCFG_DATARATE_2M)
     #error Invalid CFG_DATARATE setting
#endif
#if (CFG_NUM_ADDRESS_BYTES < 3 || CFG_NUM_ADDRESS_BYTES > 5)
     #error Invalid CFG_NUM_ADDRESS_BYTES setting
#endif

#endif